# Generated by Django 4.1.3 on 2022-11-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el Nombre del Tipo de Producto', max_length=100)),
            ],
            options={
                'verbose_name': 'tipoProducto',
                'verbose_name_plural': 'tipoProductos',
            },
        ),
    ]
