# Generated by Django 4.1.3 on 2022-11-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoProductos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion'),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edicion'),
        ),
    ]
