# Generated by Django 4.1.3 on 2022-11-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipoProductos', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipoproducto',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipoProductos.tipoproducto'),
        ),
    ]
